DROP TABLE IF EXISTS PARAMETER;
DROP TABLE IF EXISTS CLIENTS;
DROP TABLE IF EXISTS AUDIT;

CREATE TABLE PARAMETER(
    ID VARCHAR2(3) PRIMARY KEY ,
    DESCRIPTION VARCHAR2(25) NOT NULL
);

CREATE TABLE CLIENT(
    NUMBERID INT(10) PRIMARY KEY ,
    TYPEID VARCHAR2(3) NOT NULL ,
    EMAIL VARCHAR2(100) NOT NULL ,
    CELLPHONE VARCHAR2(10) NOT NULL
);

CREATE TABLE AUDIT(
    ID INT(10) PRIMARY KEY AUTO_INCREMENT,
    CLIENTINFO VARCHAR2(100) NOT NULL ,
    DATE VARCHAR2(100) NOT NULL,
    STATUS VARCHAR2(100) NOT NULL
);
